### ISSUE TITLE
Fix : Remove Item Code from Kitchen Receipt

### ISSUE THREAD

**Issue by sammish** [bailabs/tailorder-server#1]
Please Remove Item Code from Kitchen Receipt

![WhatsApp Image 2019-06-11 at 10 02 43 AM](https://user-images.githubusercontent.com/12432802/59250754-d74d5880-8c30-11e9-80b6-6194e2871641.jpeg)

**Comment by iRaySpace** [comment]
Added this on new version, append config.py with `PRINT_ITEM_CODE = False`
