### ISSUE TITLE
Fix : Don't allow selecting Dine-in & Family without table number 

### ISSUE THREAD

**Issue by sammish** [bailabs/tailorder-server#5]
![tablenumber](https://user-images.githubusercontent.com/12432802/61443633-909afe80-a952-11e9-80b0-cc0c0e5fc5a4.gif)

**Comment by iRaySpace** [comment]
Updated the TailOrder server. Will update the TailOrder.

**Comment by iRaySpace** [comment]
Check new TailOrder update.
